import os

STORAGE_CONNECTION_STRING = os.getenv("STORAGE_CONNECTION_STRING")
EVENT_GRID_TOPIC_ENDPOINT = os.getenv("EVENT_GRID_TOPIC_ENDPOINT")
EVENT_GRID_TOPIC_KEY = os.getenv("EVENT_GRID_TOPIC_KEY")

MAIL_TM_API_URL = "https://api.mail.tm"
TABLE_NAME = "Emails"
BLOB_CONTAINER_NAME = "inboxes"

