const CHECK_EMAIL_ENDPOINT = window.env.CHECK_EMAIL_ENDPOINT;
const GENERATE_EMAIL_ENDPOINT = window.env.GENERATE_EMAIL_ENDPOINT
const DELETE_EMAIL_ENDPOINT = window.env.DELETE_EMAIL_ENDPOINT
const LOAD_INBOX_ENDPOINT = window.env.LOAD_INBOX_ENDPOINT

const API_ENDPOINTS = {
    GENERATE_EMAIL_ENDPOINT,
    CHECK_EMAIL_ENDPOINT,
    LOAD_INBOX_ENDPOINT,
    DELETE_EMAIL_ENDPOINT,
};

export default API_ENDPOINTS;