name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch: # Permette l'esecuzione manuale del workflow

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      # Debug: Mostra la directory corrente e i file
      - name: Check Current Directory
        run: pwd

      - name: List Files in Current Directory
        run: ls -al

      - name: Debug Directory Structure
        run: ls -R

      # Verifica che index.html esista
      - name: Verify index.html exists
        run: |
          if [ ! -f src/index.html ]; then
            echo "Error: src/index.html not found!";
            exit 1;
          fi

      # Step per sostituire i placeholder nel file index.html
      - name: Inject environment variables into index.html and inbox.html
        run: |
          sed -i "s|__CHECK_EMAIL_ENDPOINT__|$CHECK_EMAIL_ENDPOINT|g" src/index.html
          sed -i "s|__GENERATE_EMAIL_ENDPOINT__|$GENERATE_EMAIL_ENDPOINT|g" src/index.html
          sed -i "s|__DELETE_EMAIL_ENDPOINT__|$DELETE_EMAIL_ENDPOINT|g" src/index.html
          sed -i "s|__LOAD_INBOX_ENDPOINT__|$LOAD_INBOX_ENDPOINT|g" src/index.html

          sed -i "s|__CHECK_EMAIL_ENDPOINT__|$CHECK_EMAIL_ENDPOINT|g" src/inbox.html
          sed -i "s|__GENERATE_EMAIL_ENDPOINT__|$GENERATE_EMAIL_ENDPOINT|g" src/inbox.html
          sed -i "s|__DELETE_EMAIL_ENDPOINT__|$DELETE_EMAIL_ENDPOINT|g" src/inbox.html
          sed -i "s|__LOAD_INBOX_ENDPOINT__|$LOAD_INBOX_ENDPOINT|g" src/inbox.html
        env:
          CHECK_EMAIL_ENDPOINT: ${{ secrets.CHECK_EMAIL_ENDPOINT }}
          GENERATE_EMAIL_ENDPOINT: ${{ secrets.GENERATE_EMAIL_ENDPOINT }}
          DELETE_EMAIL_ENDPOINT: ${{ secrets.DELETE_EMAIL_ENDPOINT }}
          LOAD_INBOX_ENDPOINT: ${{ secrets.LOAD_INBOX_ENDPOINT }}

      

      # Step per fare il deploy su Azure
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_FOREST_066CD5610 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "src" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_FOREST_066CD5610 }}
          action: "close"
