name: Deploy Azure Function

on:
  workflow_dispatch: # Permette l'esecuzione manuale del workflow

jobs:
  deploy-function:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debug: verifica il contenuto della directory
      - name: Debug repository content
        run: |
          ls -R

      # Imposta Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Login ad Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Installazione di Azure Functions Core Tools
      - name: Setup Azure Functions Core Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y azure-functions-core-tools-4

      # Installazione dipendenze Python
      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r az-func/requirements.txt

      # Deploy della Function App
      - name: Deploy Function App
        run: |
          cd az-func
          func azure functionapp publish SnapMailFuncApp --python --verbose
